apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gcm.fullname" . }}-backend-config
  labels:
    {{- include "gcm.labels" . | nindent 4 }}
data:
  ENVIRONMENT: {{ .Values.backend.config.environment | quote }}
  ALLOWED_ORIGINS: {{ .Values.backend.config.allowedOrigins | quote }}
  KEYCLOAK_URL: {{ .Values.backend.config.keycloakUrl | quote }}
  KEYCLOAK_REALM: {{ .Values.backend.config.keycloakRealm | quote }}
  ALLOW_TEAM_ID_FALLBACK: {{ .Values.backend.config.allowTeamIdFallback | quote }}
  WORKERS: {{ .Values.backend.workers | quote }}
