apiVersion: v1
kind: Service
metadata:
  name: {{ include "gcm.fullname" . }}-backend
  labels:
    {{- include "gcm.labels" . | nindent 4 }}
spec:
  type: ClusterIP  # nur intern erreichbar – Ingress ist der einzige Außenzugang
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    {{- include "gcm.backendSelectorLabels" . | nindent 4 }}
